---
title: "Weekly Patient Report"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rbokeh)
library(ggplot2)
library(DT)

#Part 2: #Build a flexdashboard using week 4 data, again change the charts and tables info.  Turn in the html.

# set wd
setwd("/cloud/project/lessons/9_Apr3_APIs_ReportingAutomation/wk9_data")

# Identify the file in the directory
searchPattern <- 'Wk4'
pth <- list.files(pattern = searchPattern, full.names = T)
pth <- pth[grep('*.csv', pth)]
df  <- read.csv(pth)
```

Row 
-----------------------------------------------------------------------

### Report Date

```{r date}
valueBox(Sys.Date(), 
         icon = "fa-calendar-check-o", #http://fontawesome.io/icon/calendar-check-o/
         color = "#bada55")

```

Row
-----------------------------------------------------------------------

### Length of Stay Distribution

```{r histogram, message=FALSE}
ggplot(data = df) + geom_histogram(aes(time_in_hospital))
```

Row {data-height=350}
-------------------------------------
   
### Relationships: Age vs Time in Hospital

```{r scatter1, message=FALSE}
figure(height=350) %>%
  ly_points(x=age, y=time_in_hospital,data=df ,
            hover = list(patient_id, age, time_in_hospital)) %>%
  x_axis(label='age') %>%
  y_axis(label='time in hospital') %>%
  theme_axis("x", major_label_orientation = 90) 
```   
    
### Relationships: Age vs Number of Diagnosis

```{r scatter2, message=FALSE}
figure(height=350) %>%
  ly_points(x=age, y=number_diagnoses,data=df ,hover = list(patient_id)) %>%
  x_axis(label='age') %>%
  y_axis(label='number diagnoses') %>%
  theme_axis("x", major_label_orientation = 90) 
```

Row 
-------------------------------------

### Admission Types (basic table info)

```{r table1, message=FALSE}
knitr::kable(as.matrix(table(df$admission_type_id)) )
```

### Admission Sources (better formatted table info)

```{r table2, message=FALSE}
admsx <- as.matrix(summary(df$admission_source_id))
admsx <- data.frame(amt = rownames(admsx),
                  freq = admsx[,1])
rownames(admsx) <- NULL
knitr::kable(admsx)
```

Row 
-------------------------------------

### Source File (dynamic table info)

```{r table3, message=FALSE}
DT::datatable(df[1:300,1:5], 
              options = list(bPaginate = TRUE))
```